#!/bin/bash
#
# udp          Start/Stop any shell script
#
# chkconfig: 345 95 65
# description: udp
# processname: udpd
#

# ENVIRONMENT
# Edit these for your configuration

# Name for the service, used in logging
NAME=udp

# Name of the user to be used to execute the service
SCRIPT_USER=root # pi for raspberry

# Example of how to pass paramters into the command
PARAM2=whatever

# In which directory is the shell script that this service will execute
UDP_SCRIPTS_DIR=/root/lampi

# Construct the command the will cd into the right directory, and invoke the script
#GIT_COMMAND="cd $UDP_SCRIPTS_DIR && git pull origin master"

# Construct the command the will cd into the right directory, and invoke the script
#UDP_COMMAND="cd $UDP_SCRIPTS_DIR && ./http_server.sh 'param1' $PARAM2"
UDP_COMMAND="cd $UDP_SCRIPTS_DIR && ./udp_server.sh"

# How can the script be identified if it appears in a 'ps' command via grep?
#  Examples to use are 'java', 'python' etc.
UDP_PROCESS_TYPE=ruby

# Where to write the log file?
UDP_SVC_LOG_FILE=$UDP_SCRIPTS_DIR/udp_server.log

# Where to write the process identifier - this is used to track if the service is already running
# Note: the script noted in the COMMAND must actually write this file
PID_FILE=$UDP_SCRIPTS_DIR/udp_server.pid

# Load system specific optional arguments
# Create and populate this file with machine specific settings
if [ -f /etc/sysconfig/udpd ]; then
    . /etc/sysconfig/udpd
fi

# Is the service already running? If so, capture the process id
if [ -f $PID_FILE ]; then
    PID=`cat $PID_FILE`
else
    PID=""
fi

# SERVICE ENTRY POINTS (START/STOP)

# Start Command
start() {
    if [ "${PID}" != "" ]; then
        # Check to see if the /proc dir for this process exists
        if [ -a /proc/${PID} ]; then
            # check to make sure this is likely the running service
            ps aux | grep ${PID} | grep $UDP_PROCESS_TYPE >> /dev/null
            # If it is a process of the right type assume that it is udp and just exit
            # otherwise remove the subsys lock file and start udp
            if [ "$?" = "0" ]; then
                exit 1
            else
                echo "udp lock file still exists, removing..."
                rm /var/lock/udpd
            fi
        else
            # The process running as pid $PID is not a process of the right type, remove subsys
            # lock and start udp
            echo "udp lock file still exists, removing..."
            rm /var/lock/udpd
        fi
    fi
    #echo -n "Updating repo: "
    #su - $SCRIPT_USER -c "/bin/sh -c \"$GIT_COMMAND\""
    echo -n "Starting udp: "
    su - $SCRIPT_USER -c "/bin/sh -c \"$UDP_COMMAND > $UDP_SVC_LOG_FILE 2>&1\"" & RETVAL=$?
    sleep 3
    touch /var/lock/udpd
    exit 0
}

stop() {

    echo -n $"Stopping udp: "
    if [ "${PID}" != "" ]; then
        echo -n "killing " $PID
        kill ${PID}
        for i in {1..30}
        do
            if [ -n "`ps aux | grep $UDP_PROCESS_TYPE | grep udp `" ]; then
                sleep 1 # Still running, wait a second.
                echo -n .
            else
                # stopped
                rm -f /var/lock/udpd
                rm -f $PID_FILE
                echo
                exit 0
            fi
        done
    else
        echo "$NAME is not running"
        exit 1
    fi
    echo "Failed to stop in 30 seconds."
    kill -QUIT ${PID} # Request a thread dump so we can diagnose a hung shutdown
    exit 1
}

case "$1" in
  start)
      start
    ;;
  stop)
      stop
    ;;
  *)
    echo $"Usage: $0 {start|stop}"
    exit 1
esac
